### ISSUE TITLE
RBL Bank - Unauthorized Repository Removal Request

### ISSUE THREAD

**Issue by Cybersecurity-Specialist** [unipeer/chainlink-upi-adapter#7]
Hi Github,

Our client has been strict about this repository or any program distributed online. This UPI (Unified Payment Interface), as stated and so-called partnered with our client - RBL Bank, is false. We have been adamant about our claim that this repository has no authorization or affiliation to link their program to RBL system as this may breach bank security.

As we shared and engaged in a similar industry, we sure hope you understand where we are coming from. Our report has been keen about this repository violating several rights, which we hope you uphold.

Again, our client vehemently denies affiliation nor source this script as part of their system. All programs they have and will generate should come from their Development Team alone, nothing else.

I appreciate any help you can provide.

Roger Delo
iZOOlabs Security Response 

Global Security Operations Centre 
+44 20 3734 2726 
izoolabs@izoologic.com 
www.izoologic.com

**Comment by shalzz** [comment]
The contents of this repository are completely original and all copyright and license is owned by me as the author.
Nowhere have I made a claim of this being affiliated with RBL in any official capacity or partnership. You can find the disclaimer here: https://github.com/unipeer/chainlink-upi-adapter#disclaimer

If you actually have any legal claims you are welcome to email me the documents.
